spring:
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**
          filters:
            - RewritePath=/api/employees/(?<segment>.*), /api/employees/$\{segment}
        
        - id: requirement-service
          uri: lb://requirements-service
          predicates:
            - Path=/api/requirements/**
          filters:
            - RewritePath=/api/requirements/(?<segment>.*), /api/requirements/$\{segment}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
