
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**
          filters:
            - RewritePath=/api/employees/(?<segment>.*), /api/employees/$\{segment}
        
        - id: requirement-service
          uri: lb://requirements-service
          predicates:
            - Path=/api/requirements/**
          filters:
            - RewritePath=/api/requirements/(?<segment>.*), /api/requirements/$\{segment}

server:
  port: 8080

eureka:
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
